package goldenfixtures

import (
	"archive/zip"
	"os"
	"path/filepath"
	"testing"
)

// mediaFixtures are committed under testdata/media and regenerated by the
// gen_fixtures.sh script beside them, which needs ffmpeg. Real encoder output is
// the point: it carries the padding, edit lists and seek tables that a
// hand-built container would not.
var mediaFixtures = []string{
	"sample.mp4",   // h264 and aac muxed together
	"silent.mp4",   // video with no audio track
	"sample.mov",   // the same boxes under a different extension
	"sample.m4a",   // audio only
	"sample.wav",
	"sample.flac",
	"truncated.mp4", // a header that stops mid-box
}

func SetupMediaFixture(t *testing.T) string {
	t.Helper()
	setupMockConfig(t)
	dir := t.TempDir()

	for _, name := range mediaFixtures {
		data, err := os.ReadFile(filepath.Join("testdata", "media", name))
		if err != nil {
			t.Fatalf("read fixture %s: %v", name, err)
		}
		if err := os.WriteFile(filepath.Join(dir, name), data, 0644); err != nil {
			t.Fatalf("write fixture %s: %v", name, err)
		}
	}

	writeFile(t, dir, "notes.txt", "beside the media\n", 0644)
	createMediaZip(t, filepath.Join(dir, "media.zip"))

	return dir
}

// createMediaZip covers extraction from an archive entry, which is read through
// a different path than a file on disk.
func createMediaZip(t *testing.T, path string) {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("testdata", "media", "sample.wav"))
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}

	f, err := os.Create(path)
	if err != nil {
		t.Fatalf("create zip: %v", err)
	}
	defer f.Close()

	w := zip.NewWriter(f)
	entry, err := w.Create("clip.wav")
	if err != nil {
		t.Fatalf("create zip entry: %v", err)
	}
	if _, err := entry.Write(data); err != nil {
		t.Fatalf("write zip entry: %v", err)
	}
	if err := w.Close(); err != nil {
		t.Fatalf("close zip: %v", err)
	}
}
